// This endpoint reads the cached report generated by the cron job
// If no cache exists, triggers a fresh generation
export const config = { maxDuration: 60 }

import { generateReport } from './generate-report'

// Simple file-based cache using /tmp (persists within same serverless instance)
import fs from 'fs'
const CACHE_FILE = '/tmp/cc-report-cache.json'

function readCache() {
  try {
    if (fs.existsSync(CACHE_FILE)) {
      const data = JSON.parse(fs.readFileSync(CACHE_FILE, 'utf8'))
      const age = Date.now() - new Date(data.generatedAt).getTime()
      // Cache valid for 23 hours
      if (age < 23 * 60 * 60 * 1000) return data
    }
  } catch(e) {}
  return null
}

function writeCache(data) {
  try { fs.writeFileSync(CACHE_FILE, JSON.stringify(data)) } catch(e) {}
}

export default async function handler(req, res) {
  const force = req.query.force === 'true'

  // Try cache first
  if (!force) {
    const cached = readCache()
    if (cached) {
      return res.status(200).json({ ...cached, fromCache: true })
    }
  }

  // Generate fresh report
  try {
    const queryIds = {
      campaigns:   req.query.campaigns,
      devices:     req.query.devices,
      locations:   req.query.locations,
      shopping:    req.query.shopping,
      searchTerms: req.query.searchTerms,
    }
    const report = await generateReport(req.headers.host, queryIds)
    writeCache(report)
    res.status(200).json({ ...report, fromCache: false })
  } catch(e) {
    res.status(500).json({ ok: false, error: e.message })
  }
}
